solution for dz5-calendar
js-tasks-ru/htmlcss-20220616_alina-polovneva pull request #10
Opened 2022-07-11 11:19 UTC by AlinaPolo

2022-07-11 11:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-07-11 11:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-11 13:55 UTC, GSemikozov requested changes

2022-07-11 13:55 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +    align-items: flex-start;
а отступ снизу точно будет по макету?

2022-07-11 14:03 UTC, AlinaPolo commented on 05-lection3/03-calendar/calendar.css
> +    align-items: flex-start;
проверяла по perfectpixel,с макетом совпадает.
![image](https://user-images.githubusercontent.com/107675534/178282150-d1ca01e3-e651-44ec-a13b-835f20c4063f.png)

2022-07-11 14:19 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-07-12 13:52 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-12 14:01 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-07-15 19:37 UTC, GSemikozov approved these changes

2022-07-15 19:37 UTC, merged